const API = 'https://api.erpimpar.com.br/rh/combustivel/';
let COLABS = [];
const $ = id => document.getElementById(id);
const money = v => 'R$ ' + (Number(v)||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc = s => String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function getUser(){try{return JSON.parse(localStorage.getItem('ERPIMPAR_USER')||sessionStorage.getItem('ERPIMPAR_USER')||'null')}catch{return null}}
function loadUser(){const u=getUser();const nome=u?(u.nome||u.Nome||'Usuário RP'):'Usuário RP';$('userName').textContent=nome;$('userEmail').textContent=u?(u.email||u.Email||'sessão local'):'sessão local';$('avatar').textContent=(nome||'U').trim().slice(0,1).toUpperCase();}
async function fetchJson(url, opts){const r=await fetch(url,opts||{cache:'no-store'});const t=await r.text();let j={};try{j=t?JSON.parse(t):{};}catch{throw new Error(t||'Resposta inválida do servidor');}if(!r.ok||j.ok===false)throw new Error(j.erro||('HTTP '+r.status));return j;}
function toast(title,msg,type='ok'){const el=document.createElement('div');el.className='toast-rp '+(type==='error'?'error':'');el.innerHTML=`<div class="toast-ico">${type==='error'?'!':'✓'}</div><div><div class="toast-title">${esc(title)}</div><div class="toast-msg">${esc(msg)}</div></div><button class="toast-close">×</button>`;el.querySelector('button').onclick=()=>el.remove();$('toastWrap').appendChild(el);setTimeout(()=>el.remove(),5200);}
function log(obj){$('logBox').textContent=typeof obj==='string'?obj:JSON.stringify(obj,null,2);}
function collect(){return [...document.querySelectorAll('.colab-item')].map(row=>({nome_original:row.dataset.nome,nome_normalizado:row.querySelector('.norm').value.trim().toUpperCase(),obras:row.querySelector('.check').checked}));}
function updateKpis(){const sel=collect().filter(x=>x.obras).length;$('kColabs').textContent=COLABS.length||'-';$('kSelecionados').textContent=sel||'-';}
function renderColabs(){const html=COLABS.map((c,i)=>`<div class="colab-item ${c.obras?'':'off'}" data-nome="${esc(c.nome_original)}"><input class="check" type="checkbox" ${c.obras?'checked':''}><div><div class="name">${esc(c.nome_original)}</div><div class="meta">${esc((c.fontes||[]).join(' + '))} • ${c.registros||0} registros</div></div><input class="norm" value="${esc(c.nome_normalizado||c.nome_original)}" title="Nome normalizado no JSON"><div class="badge">OBRAS</div></div>`).join('');$('colabList').innerHTML=html||'<div class="muted">Nenhum colaborador carregado.</div>';document.querySelectorAll('.check').forEach(ch=>ch.addEventListener('change',e=>{e.target.closest('.colab-item').classList.toggle('off',!e.target.checked);updateKpis();}));document.querySelectorAll('.norm').forEach(inp=>inp.addEventListener('input',updateKpis));updateKpis();}
async function carregar(){try{log('Lendo planilhas no KingHost...');const j=await fetchJson(API+'listar_colaboradores.php');COLABS=j.data||[];renderColabs();log(j);toast('Colaboradores carregados',`${COLABS.length} nomes encontrados nas planilhas.`);}catch(e){log(e.message);toast('Falha ao carregar',e.message,'error');}}
async function salvarConfig(){try{const colaboradores=collect();const j=await fetchJson(API+'salvar_config.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({colaboradores})});log(j);toast('Seleção salva','Configuração de colaboradores gravada no servidor.');}catch(e){log(e.message);toast('Falha ao salvar',e.message,'error');}}
async function gerar(){try{const colaboradores=collect();log('Gerando JSON consolidado...');const j=await fetchJson(API+'gerar_combustivel.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({colaboradores})});$('kRegistros').textContent=j.registros||0;$('kValor').textContent=money(j.valor_total);log(j);toast('Base gerada',`${j.registros||0} registros consolidados em JSON.`);await carregarResumo();}catch(e){log(e.message);toast('Falha ao gerar',e.message,'error');}}
async function carregarResumo(){try{const j=await fetchJson(API+'data/combustivel_resumo.json?ts='+Date.now());const rows=j.por_colaborador||[];$('tbodyResumo').innerHTML=rows.map(r=>`<tr><td>${esc(r.colaborador)}</td><td>${money(r.valor)}</td></tr>`).join('')||'<tr><td colspan="2">Sem resumo gerado.</td></tr>';$('kRegistros').textContent=j.total_registros||'-';$('kValor').textContent=money(j.valor_total);}catch{}}
async function status(){try{const j=await fetchJson(API+'status.php');log(j);toast('Status consultado','Arquivos e estrutura conferidos.');}catch(e){log(e.message);toast('Falha no status',e.message,'error');}}
$('btnCarregar').addEventListener('click',carregar);$('btnSalvarConfig').addEventListener('click',salvarConfig);$('btnGerar').addEventListener('click',gerar);$('btnStatus').addEventListener('click',status);
loadUser();carregarResumo();
