const API = 'https://api.erpimpar.com.br/rh/combustivel/';
let COLABS = [];
const $ = id => document.getElementById(id);
const money = v => 'R$ ' + (Number(v)||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc = s => String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function getUser(){try{return JSON.parse(localStorage.getItem('ERPIMPAR_USER')||sessionStorage.getItem('ERPIMPAR_USER')||'null')}catch{return null}}
function loadUser(){const u=getUser();$('userName').textContent=u?(u.nome||u.Nome||'Usuário RP'):'Usuário RP';$('userEmail').textContent=u?(u.email||u.Email||'sessão local'):'sessão local'}
function toast(title,msg,type='ok'){const el=document.createElement('div');el.className='toast '+(type==='error'?'error':'');el.innerHTML=`<div class="toast-ico">${type==='error'?'!':'✓'}</div><div><div class="toast-title">${esc(title)}</div><div class="toast-msg">${esc(msg)}</div></div><button class="toast-close">×</button>`;$('toastWrap').appendChild(el);el.querySelector('button').onclick=()=>el.remove();setTimeout(()=>el.remove(),5200)}
async function api(path, opts={}){const r=await fetch(API+path,{cache:'no-store',...opts});const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch{throw new Error(text.slice(0,800)||'Resposta inválida do servidor')};if(!r.ok||j.ok===false)throw new Error(j.erro||j.detalhe||('HTTP '+r.status));return j}
function setLog(obj){$('log').textContent=typeof obj==='string'?obj:JSON.stringify(obj,null,2)}
function resumo(){const filtradas = COLABS.filter(c=>c.obra);$('kSel').textContent=filtradas.length;$('kReg').textContent=COLABS.reduce((a,c)=>a+(Number(c.registros)||0),0).toLocaleString('pt-BR');$('kValor').textContent=money(filtradas.reduce((a,c)=>a+(Number(c.valor_total)||0),0));$('countPill').textContent=COLABS.length+' colaboradores'}
function render(){const q=$('busca').value.trim().toLowerCase();const rows=COLABS.filter(c=>!q||String(c.nome_origem).toLowerCase().includes(q)||String(c.normalizado).toLowerCase().includes(q));$('lista').innerHTML=rows.length?rows.map((c)=>{const idx=COLABS.indexOf(c);return `<div class="person ${c.obra?'':'off'}"><input class="check" type="checkbox" ${c.obra?'checked':''} onchange="toggleColab(${idx},this.checked)"><div><div class="name">${esc(c.nome_origem)}</div><div class="meta">${esc((c.fontes||[]).join(' + '))} • ${Number(c.registros||0).toLocaleString('pt-BR')} registros</div></div><input value="${esc(c.normalizado||c.nome_origem)}" onchange="normalizar(${idx},this.value)" placeholder="Nome normalizado"><div class="money">${money(c.valor_total)}</div><div class="src">${c.obra?'OBRAS':'IGNORAR'}</div></div>`}).join(''):'<div class="empty">Nenhum colaborador encontrado.</div>';resumo()}
window.toggleColab=(idx,val)=>{COLABS[idx].obra=!!val;render()};
window.normalizar=(idx,val)=>{COLABS[idx].normalizado=val||COLABS[idx].nome_origem;resumo()};
async function carregar(){try{setLog('Lendo planilhas no KingHost...');const j=await api('listar_colaboradores.php');COLABS=j.colaboradores||[];render();setLog(j);toast('Colaboradores carregados',`${COLABS.length} nomes encontrados nas planilhas.`)}catch(e){setLog(e.message);toast('Erro ao carregar',e.message,'error')}}
async function status(){try{const j=await api('status.php');setLog(j);toast('Status carregado',j.vendor_encontrado?'Vendor encontrado.':'Vendor não encontrado.','ok')}catch(e){setLog(e.message);toast('Erro no status',e.message,'error')}}
async function salvar(){try{const payload={colaboradores:COLABS.map(c=>({nome_origem:c.nome_origem,normalizado:c.normalizado||c.nome_origem,obra:!!c.obra}))};const j=await api('salvar_config.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setLog(j);toast('Seleção salva','Configuração de colaboradores gravada no KingHost.')}catch(e){setLog(e.message);toast('Erro ao salvar',e.message,'error')}}
async function gerar(){try{await salvar();setLog('Gerando combustivel.json...');const j=await api('gerar_combustivel.php');setLog(j);toast('Base gerada',`${j.total_registros||0} registros importados • ${money(j.total_valor)}`)}catch(e){setLog(e.message);toast('Erro ao gerar',e.message,'error')}}
document.addEventListener('DOMContentLoaded',()=>{loadUser();$('btnStatus').onclick=status;$('btnCarregar').onclick=carregar;$('btnSalvar').onclick=salvar;$('btnGerar').onclick=gerar;$('btnTodos').onclick=()=>{COLABS.forEach(c=>c.obra=true);render()};$('btnNenhum').onclick=()=>{COLABS.forEach(c=>c.obra=false);render()};$('busca').oninput=render;});
