/* consulta_json_v1.js — Patch isolado da Pesquisa (RISCO ZERO) */
(function(){
  var JSON_URL = 'https://api.erpimpar.com.br/gerador/json_table_cors.php';
  var SAVE_TOKEN = '8ce29ab4b2d531b0eca93b9cfc4538042a6b9f3a8882e543cbad73663b77';
  function el(tag, attrs, html){var e=document.createElement(tag);if(attrs){Object.keys(attrs).forEach(function(k){e.setAttribute(k,attrs[k]);});}if(html!=null)e.innerHTML=html;return e;}
  function ensureStyles(){if(document.getElementById('consulta_json_v1_styles'))return;var css=['#cj_modal{position:fixed;inset:0;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.5);z-index:999999;}','#cj_box{background:#fff;border-radius:10px;width:92%;max-width:900px;padding:14px;box-shadow:0 10px 30px rgba(0,0,0,.2);}','#cj_head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;font-weight:700;}','#cj_table{width:100%;border-collapse:collapse;}','#cj_table th,#cj_table td{padding:8px;border-bottom:1px solid #eee;text-align:left;}','#cj_close{border:none;background:#eee;padding:6px 10px;border-radius:8px;cursor:pointer;}','.cj_row{cursor:pointer;}'].join('');var style=el('style',{id:'consulta_json_v1_styles'},css);document.head.appendChild(style);}
  function buildModal(){if(document.getElementById('cj_modal'))return;ensureStyles();var modal=el('div',{id:'cj_modal'});var box=el('div',{id:'cj_box'});var head=el('div',{id:'cj_head'},'<div>Consulta de documentos (Excel)</div>');var btnClose=el('button',{id:'cj_close'},'Fechar');btnClose.onclick=function(){modal.style.display='none';};head.appendChild(btnClose);var table=el('table',{id:'cj_table'});table.innerHTML='<thead><tr><th>Código</th><th>Data</th><th>Contratante</th></tr></thead><tbody id="cj_body"><tr><td colspan="3">Carregando...</td></tr></tbody>';box.appendChild(head);box.appendChild(table);modal.appendChild(box);document.body.appendChild(modal);}
  function openModal(){buildModal();document.getElementById('cj_modal').style.display='flex';}
  function loadList(){var url=JSON_URL+'?op=list'+(SAVE_TOKEN?'&token='+encodeURIComponent(SAVE_TOKEN):'');return fetch(url,{credentials:'include'}).then(function(r){return r.json();});}
  function renderList(items){var body=document.getElementById('cj_body');if(!body)return;body.innerHTML='';if(!items||!items.length){body.innerHTML='<tr><td colspan="3">Sem registros.</td></tr>';return;}items.forEach(function(row){var tr=el('tr',{class:'cj_row'});tr.innerHTML='<td>'+(row.codigo||'')+'</td><td>'+((row.data_criacao||'').slice(0,10))+'</td><td>'+(row.nomeContratante||'')+'</td>';tr.onclick=function(){openActions(row.codigo||'');};body.appendChild(tr);});}
  function openActions(codigo){if(!codigo)return;if(confirm('Documento '+codigo+'\n\nOK = Atualizar dados\nCancelar = Baixar Excel')){getDoc(codigo).then(fillForm).catch(function(){alert('Falha ao carregar dados.');});}else{alert('Para baixar o Excel, abra /www/api/storage/docs e localize o arquivo do código '+codigo+'.');}}
  function getDoc(codigo){var url=JSON_URL+'?op=get&codigo='+encodeURIComponent(codigo)+(SAVE_TOKEN?'&token='+encodeURIComponent(SAVE_TOKEN):'');return fetch(url,{credentials:'include'}).then(function(r){return r.json();}).then(function(j){if(!j||!j.ok||!j.item)throw new Error('not_found');return j.item;});}
  function fillForm(data){try{Object.keys(data).forEach(function(k){var elx=document.getElementById(k);if(elx&&'value'in elx){elx.value=data[k];}});document.getElementById('cj_modal').style.display='none';window.scrollTo({top:0,behavior:'smooth'});}catch(e){}}
  function onClickSearch(){openModal();loadList().then(function(j){if(!j||!j.ok){document.getElementById('cj_body').innerHTML='<tr><td colspan="3" style="color:#900;">Erro ao carregar a lista.</td></tr>';return;}renderList(j.items||[]);}).catch(function(){document.getElementById('cj_body').innerHTML='<tr><td colspan="3" style="color:#900;">Erro ao carregar a lista.</td></tr>';});}
  function init(){var btn=document.getElementById('searchJsonBtn');if(!btn)return;btn.addEventListener('click',function(ev){ev.preventDefault();onClickSearch();});}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();