(() => {
 const C=window.IMPAR_SURVEY_CONFIG||{};
 const steps=["intro","profile","sites","video","logos","final","thanks"];
 let current=0,watched=0,lastVideoTime=0,videoPosition=0,resumeToken=null,saveTimer=null,isSaving=false,restored=false;
 const siteQ=[["trust","Qual transmite mais confiança?"],["modern","Qual parece mais moderna e atual?"],["engineering","Qual comunica melhor engenharia e capacidade técnica?"],["size","Qual parece uma empresa mais estruturada e preparada para projetos de maior porte?"],["clarity","Qual explica melhor o que a empresa faz?"],["contact","Se você precisasse contratar hoje, qual delas teria maior chance de gerar contato?"]];
 const logoQ=[["trust","Confiança"],["modern","Modernidade"],["engineering","Engenharia / capacidade técnica"],["technology","Tecnologia"],["premium","Sofisticação / percepção premium"],["size","Porte / estrutura"],["memorable","Memorabilidade"],["fit","Representa melhor a empresa mostrada no vídeo"]];
 const data={version:C.VERSION||"V2",started_at:new Date().toISOString(),order:{},respondent:{},answers:{site:{},video:{},logo:{},final:{}},meta:{screen:`${screen.width}x${screen.height}`,user_agent:navigator.userAgent}};
 const rnd=()=>Math.random()<.5;
 function newOrder(){data.order.site=rnd()?{A:"current",B:"proposed"}:{A:"proposed",B:"current"};data.order.logo=rnd()?{A:"current",B:"proposed"}:{A:"proposed",B:"current"}}
 function optionChoice(group,key,title){return `<div class="q"><div class="q-title">${title}</div><div class="choices">${["A","B","Igual"].map(v=>`<label class="choice"><input type="radio" name="${group}_${key}" value="${v}"><span>${v==="Igual"?"Sem diferença":`Opção ${v}`}</span></label>`).join("")}</div></div>`}
 function buildQuestions(){document.querySelector('#siteQuestions').innerHTML=siteQ.map(q=>optionChoice('site',...q)).join('');document.querySelector('#logoQuestions').innerHTML=logoQ.map(q=>optionChoice('logo',...q)).join('');document.querySelectorAll('[data-scale]').forEach(el=>{const key=el.dataset.scale;el.innerHTML=Array.from({length:11},(_,i)=>`<label><input type="radio" name="${key}" value="${i}"><span>${i}</span></label>`).join('')})}
 function siteCard(letter,kind){const url=kind==='current'?C.SITE_CURRENT_URL:C.SITE_PROPOSED_URL;return `<article class="option"><div class="option-head"><span class="option-tag">OPÇÃO ${letter}</span><button class="option-open" onclick="window.open('${url}','_blank','noopener')">Abrir em nova aba ↗</button></div><div class="site-frame"><iframe src="${url}" title="Opção ${letter}" loading="lazy"></iframe><div class="frame-hint">Navegue pela opção ${letter}. Se o site bloquear a visualização incorporada, abra em nova aba.</div></div></article>`}
 function logoCard(letter,kind){const src=kind==='current'?C.LOGO_CURRENT:C.LOGO_PROPOSED;return `<article class="option"><div class="option-head"><span class="option-tag">OPÇÃO ${letter}</span></div><div class="logo-stage"><img src="${src}" alt="Logo opção ${letter}"></div></article>`}
 function buildOptions(){document.querySelector('#siteCompare').innerHTML=siteCard('A',data.order.site.A)+siteCard('B',data.order.site.B);document.querySelector('#logoCompare').innerHTML=logoCard('A',data.order.logo.A)+logoCard('B',data.order.logo.B)}
 const video=document.querySelector('#institutionalVideo'),vErr=document.querySelector('#videoError'),vErrText=document.querySelector('#videoErrorText'),vTech=document.querySelector('#videoTech');
 function setupVideo(){video.src=C.VIDEO_URL;video.poster=C.VIDEO_POSTER||'';vTech.textContent=`Fonte: ${C.VIDEO_URL}`;video.addEventListener('loadedmetadata',()=>{vErr.classList.remove('show');vTech.textContent=`Vídeo carregado • ${Math.round(video.duration)}s`;if(videoPosition>0&&videoPosition<video.duration-2){try{video.currentTime=videoPosition}catch(e){}}});video.addEventListener('error',()=>{vErr.classList.add('show');const code=video.error?.code||'?';vErrText.textContent=`Falha ao carregar o vídeo (código ${code}). Confirme o arquivo otimizado no KingHost.`});video.addEventListener('timeupdate',()=>{const t=video.currentTime||0;if(t>lastVideoTime&&t-lastVideoTime<2)watched+=(t-lastVideoTime);lastVideoTime=t;videoPosition=t;document.querySelector('#watchInfo').textContent=`Tempo assistido: ${Math.round(watched)}s`;if(Math.round(t)%15===0)scheduleAutosave()});video.addEventListener('pause',scheduleAutosave)}
 function setupVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;document.querySelectorAll('[data-voice-for]').forEach(btn=>{const target=document.getElementById(btn.dataset.voiceFor);const live=document.querySelector(`[data-live-for="${btn.dataset.voiceFor}"]`);if(!SR){btn.disabled=true;btn.title='Transcrição por voz não disponível neste navegador';live.textContent='Neste navegador, use o microfone do teclado do celular ou digite.';return}let rec=null,listening=false,base='';btn.addEventListener('click',()=>{if(listening){rec.stop();return}rec=new SR();rec.lang='pt-BR';rec.continuous=true;rec.interimResults=true;base=target.value.trim();rec.onstart=()=>{listening=true;btn.classList.add('listening');btn.textContent='⏹ Parar';live.textContent='Ouvindo…'};rec.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const txt=e.results[i][0].transcript;if(e.results[i].isFinal)final+=txt+' ';else interim+=txt}if(final){base=(base+' '+final).trim();target.value=base;target.dispatchEvent(new Event('input',{bubbles:true}))}live.textContent=interim?`“${interim}”`:'Ouvindo…'};rec.onerror=e=>{live.textContent=e.error==='not-allowed'?'Permissão do microfone negada. Libere o microfone no navegador.':`Não foi possível transcrever (${e.error}).`};rec.onend=()=>{listening=false;btn.classList.remove('listening');btn.textContent='🎙️ Falar';if(live.textContent==='Ouvindo…')live.textContent=''};try{rec.start()}catch(e){live.textContent='Não foi possível iniciar o microfone.'}})})}
 function radioVal(name){return document.querySelector(`input[name="${name}"]:checked`)?.value??null}
 function setRadio(name,value){if(value===null||value===undefined)return;const el=document.querySelector(`input[name="${name}"][value="${CSS.escape(String(value))}"]`);if(el)el.checked=true}
 function collect(){data.respondent.role=document.querySelector('#role').value;data.respondent.familiarity=document.querySelector('#familiarity').value;siteQ.forEach(([k])=>data.answers.site[k]=radioVal(`site_${k}`));logoQ.forEach(([k])=>data.answers.logo[k]=radioVal(`logo_${k}`));data.answers.video.complexity=radioVal('video_complexity');data.answers.video.trust=radioVal('video_trust');data.answers.video.words=document.querySelector('#video_words').value.trim();data.answers.video.watched_seconds=Math.round(watched);data.answers.video.position_seconds=Math.round(videoPosition);data.answers.final.consideration=radioVal('consideration');data.answers.final.phrase=document.querySelector('#final_phrase').value.trim();data.answers.final.comment=document.querySelector('#final_comment').value.trim()}
 function restoreUI(){document.querySelector('#role').value=data.respondent.role||'';document.querySelector('#familiarity').value=data.respondent.familiarity||'';siteQ.forEach(([k])=>setRadio(`site_${k}`,data.answers.site[k]));logoQ.forEach(([k])=>setRadio(`logo_${k}`,data.answers.logo[k]));setRadio('video_complexity',data.answers.video.complexity);setRadio('video_trust',data.answers.video.trust);setRadio('consideration',data.answers.final.consideration);document.querySelector('#video_words').value=data.answers.video.words||'';document.querySelector('#final_phrase').value=data.answers.final.phrase||'';document.querySelector('#final_comment').value=data.answers.final.comment||'';watched=Number(data.answers.video.watched_seconds||0);videoPosition=Number(data.answers.video.position_seconds||0);document.querySelector('#watchInfo').textContent=`Tempo assistido: ${Math.round(watched)}s`}
 function validStep(){collect();if(current===1&&(!data.respondent.role||!data.respondent.familiarity)){alert('Selecione seu perfil e o quanto conhece a IMPAR.');return false}if(current===2&&siteQ.some(([k])=>!data.answers.site[k])){alert('Responda todas as comparações do site.');return false}if(current===3&&(data.answers.video.complexity===null||data.answers.video.trust===null)){alert('Dê uma nota às duas perguntas após o vídeo.');return false}if(current===4&&logoQ.some(([k])=>!data.answers.logo[k])){alert('Responda todos os atributos das logos.');return false}if(current===5&&data.answers.final.consideration===null){alert('Informe a nota de consideração da IMPAR.');return false}return true}
 function updateAutosave(text,cls=''){const el=document.querySelector('#autosaveState');el.textContent=text;el.className=`autosave ${cls}`}
 function resumeUrl(){const u=new URL(location.href);u.search='';u.hash='';if(resumeToken)u.searchParams.set('r',resumeToken);return u.toString()}
 function applyTokenToUrl(){if(!resumeToken)return;const u=new URL(location.href);u.searchParams.set('r',resumeToken);history.replaceState(null,'',u)}
 async function saveDraft({silent=true,keepalive=false}={}){if(current<=0||current>=6)return null;if(isSaving&&!keepalive)return resumeToken;collect();if(!silent)updateAutosave('Salvando…','saving');else updateAutosave('Salvando…','saving');isSaving=true;try{const payload={version:data.version,started_at:data.started_at,order:data.order,respondent:data.respondent,answers:data.answers,meta:data.meta};const body=new URLSearchParams({token:resumeToken||'',current_step:String(current),watched_seconds:String(Math.round(watched)),video_position:String(Math.round(videoPosition)),payload:JSON.stringify(payload)});const r=await fetch(`${C.API_BASE}/draft_save.php`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body,keepalive});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'save_failed');resumeToken=j.token;applyTokenToUrl();updateAutosave('Salvo','saved');return resumeToken}catch(e){updateAutosave('Não salvo','error');if(!silent)alert('Não foi possível salvar agora. Verifique sua conexão e tente novamente.');return null}finally{isSaving=false}}
 function scheduleAutosave(){if(current<=0||current>=6)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft({silent:true}),1100)}
 async function loadDraft(token){try{const r=await fetch(`${C.API_BASE}/draft_get.php?token=${encodeURIComponent(token)}&ts=${Date.now()}`);const j=await r.json();if(!r.ok||!j.ok)return false;resumeToken=token;const p=j.draft?.payload||{};Object.assign(data,{version:p.version||data.version,started_at:p.started_at||data.started_at,order:p.order||data.order,respondent:p.respondent||{},answers:p.answers||data.answers,meta:p.meta||data.meta});current=Math.max(1,Math.min(5,Number(j.draft?.current_step||1)));watched=Number(j.draft?.watched_seconds||data.answers.video?.watched_seconds||0);videoPosition=Number(j.draft?.video_position||data.answers.video?.position_seconds||0);restored=true;return true}catch(e){return false}}
 function openResumeModal(){document.querySelector('#resumeLink').value=resumeUrl();document.querySelector('#resumeModal').classList.add('open');document.querySelector('#resumeModal').setAttribute('aria-hidden','false')}
 function closeResumeModal(){document.querySelector('#resumeModal').classList.remove('open');document.querySelector('#resumeModal').setAttribute('aria-hidden','true')}
 function render(){document.querySelector('#intro').style.display=current===0?'block':'none';document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===steps[current]));const labels=['Início','Perfil','Sites','Vídeo','Logos','Fechamento','Concluído'];document.querySelector('#stepLabel').textContent=labels[current];document.querySelector('#progress').style.width=`${Math.min(100,(current/(steps.length-1))*100)}%`;const saveBtn=document.querySelector('#saveExit');saveBtn.hidden=!(current>=1&&current<=5);scrollTo({top:0,behavior:'smooth'})}
 async function start(){newOrder();const tokenFromUrl=new URLSearchParams(location.search).get('r');if(tokenFromUrl){const ok=await loadDraft(tokenFromUrl);if(!ok){const u=new URL(location.href);u.searchParams.delete('r');history.replaceState(null,'',u);newOrder()}}buildQuestions();buildOptions();setupVideo();setupVoice();restoreUI();if(restored){document.querySelector('#resumeBanner').hidden=false;updateAutosave('Retomada','saved')}render();document.addEventListener('input',scheduleAutosave);document.addEventListener('change',scheduleAutosave)}
 document.addEventListener('click',async e=>{if(e.target.closest('[data-next]')){if(current>0&&!validStep())return;if(current===0){current=1;render();await saveDraft({silent:false});return}current=Math.min(steps.length-1,current+1);render();await saveDraft({silent:true})}if(e.target.closest('[data-prev]')){current=Math.max(0,current-1);render();await saveDraft({silent:true})}})
 document.querySelector('#saveExit').addEventListener('click',async()=>{const t=await saveDraft({silent:false});if(t)openResumeModal()});document.querySelector('#resumeClose').onclick=closeResumeModal;document.querySelector('#resumeBack').onclick=closeResumeModal;document.querySelector('#resumeModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeResumeModal()});document.querySelector('#resumeExit').href=C.EXIT_URL||'https://www.imparsistemas.com/';document.querySelector('#copyResume').onclick=async()=>{const input=document.querySelector('#resumeLink');try{await navigator.clipboard.writeText(input.value);document.querySelector('#resumeCopyStatus').textContent='Link copiado.'}catch(e){input.select();document.execCommand('copy');document.querySelector('#resumeCopyStatus').textContent='Link copiado.'}}
 document.querySelector('#submitSurvey').addEventListener('click',async()=>{if(!validStep())return;collect();data.completed_at=new Date().toISOString();const box=document.querySelector('#submitStatus'),btn=document.querySelector('#submitSurvey');btn.disabled=true;box.className='status info';box.textContent='Enviando respostas…';try{const body=new URLSearchParams({payload:JSON.stringify(data),resume_token:resumeToken||''});const r=await fetch(`${C.API_BASE}/submit.php`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Falha ao enviar');box.className='status ok';box.textContent=j.already_submitted?'Esta pesquisa já havia sido registrada.':'Resposta registrada.';current=6;const u=new URL(location.href);u.searchParams.delete('r');history.replaceState(null,'',u);resumeToken=null;render()}catch(err){box.className='status error';box.textContent=`Não foi possível registrar no servidor: ${err.message}. Verifique a API.`;btn.disabled=false}})
 addEventListener('beforeunload',()=>{if(resumeToken&&current>=1&&current<=5){collect();const payload={version:data.version,started_at:data.started_at,order:data.order,respondent:data.respondent,answers:data.answers,meta:data.meta};const body=new URLSearchParams({token:resumeToken,current_step:String(current),watched_seconds:String(Math.round(watched)),video_position:String(Math.round(videoPosition)),payload:JSON.stringify(payload)});fetch(`${C.API_BASE}/draft_save.php`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body,keepalive:true}).catch(()=>{})}})
 start();
})();