const API_ROOT='https://api.erpimpar.com.br';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function tick(){const d=new Date(); const de=$('.date'), he=$('.hour'); if(de)de.textContent=d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}); if(he)he.textContent=d.toLocaleTimeString('pt-BR');}
setInterval(tick,1000); addEventListener('DOMContentLoaded',tick);
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();}
function compact(s){return norm(s).replace(/\s+/g,'');}
function normId(v){const n=String(v||'').replace(/\D/g,''); return n?n.padStart(3,'0'):'';}
function arr(x){return Array.isArray(x)?x:Array.isArray(x?.data)?x.data:Array.isArray(x?.data?.projetos)?x.data.projetos:Array.isArray(x?.projetos)?x.projetos:Array.isArray(x?.items)?x.items:Array.isArray(x?.itens)?x.itens:Array.isArray(x?.obras)?x.obras:[];}
function pick(o,keys,def=''){for(const k of keys){const v=o?.[k]; if(v!==undefined&&v!==null&&String(v).trim()!=='')return v;} return def;}
async function getJson(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'t='+Date.now(),{cache:'no-store'}); if(!r.ok)throw new Error(url+' '+r.status); return r.json();}
async function firstJson(urls){let last=null; for(const u of urls){try{return await getJson(u)}catch(e){last=e}} throw last||new Error('sem fonte');}
function parseDate(s){if(!s)return null; let raw=String(s).trim(); if(!raw)return null; if(/^\d{2}\/\d{2}\/\d{4}/.test(raw)){const [d,m,y]=raw.slice(0,10).split('/'); raw=`${y}-${m}-${d}`+raw.slice(10)} const dt=new Date(raw.replace(' ','T')); return isNaN(dt)?null:dt;}
function daysSince(s){const d=parseDate(s); if(!d)return 9999; const today=new Date(); today.setHours(12,0,0,0); const ref=new Date(d); ref.setHours(12,0,0,0); return Math.max(0,Math.floor((today-ref)/86400000));}
function money(n){return (Number(n)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function initials(name){const p=String(name||'').trim().split(/\s+/).filter(Boolean); return ((p[0]?.[0]||'U')+(p.length>1?p[p.length-1][0]:'' )).toUpperCase();}
function extractCoord(o){const v=norm(pick(o,['coordenador','Coordenador','responsavel','responsável','usuario','owner','coord'],'')); if(v.includes('PABLO'))return 'PABLO'; if(v.includes('FABIO'))return 'FABIO'; if(v.includes('NICOLAS'))return 'NICOLAS'; return v||'SEM COORD.';}
function extractName(o){return String(pick(o,['nome','Nome','obra','obra_nome','projeto','titulo','name','title'],'')).trim();}
function extractUpdated(o){return pick(o,['data_atualizacao','ultima_atualizacao','ultimaAtualizacao','updated_at','updatedAt','dataAtualizacao','atualizado_em','modificado_em','lastUpdate'],'');}
function extractReal(o){const c=[o?.percentual_realizado,o?.realizado,o?.pct_real,o?.progresso_real,o?.percentual_real,o?.real,o?.percentualRealizado,o?.resumo?.percentual_realizado,o?.resumo?.real]; for(const v of c){if(v!==undefined&&v!==null&&v!==''){const n=Number(String(v).replace('%','').replace(',','.')); if(Number.isFinite(n))return n;}} return 0;}
function similarity(a,b){a=norm(a);b=norm(b); if(!a||!b)return 0; if(a===b)return 1; if(a.includes(b)||b.includes(a))return .9; const A=new Set(a.split(' ').filter(x=>x.length>2)); const B=new Set(b.split(' ').filter(x=>x.length>2)); let inter=0; A.forEach(x=>B.has(x)&&inter++); return inter/Math.max(A.size,B.size,1);}
async function obrasAtivas(){const j=await firstJson([`${API_ROOT}/cronograma/listar_obras.php`,`${API_ROOT}/cronograma/listar_kpi.php`]); return arr(j).map(o=>({raw:o,id:normId(o.id||o.codigo||o.cronograma_id||o.farol_id),nome:extractName(o),coord:extractCoord(o),updatedAt:extractUpdated(o),real:extractReal(o)})).filter(o=>o.nome&&o.real<100);}
async function cronKpi(){try{const j=await firstJson([`${API_ROOT}/cronograma/listar_kpi.php`,`${API_ROOT}/cronograma/listar_obras.php`]);return arr(j).map(o=>({raw:o,id:normId(o.id||o.codigo||o.cronograma_id||o.farol_id),nome:extractName(o),coord:extractCoord(o),updatedAt:extractUpdated(o),dias:daysSince(extractUpdated(o)),real:extractReal(o)})).filter(o=>o.nome&&o.real<100)}catch(e){return await obrasAtivas();}}
async function tvProjetos(){const j=await firstJson([`${API_ROOT}/tv/listar.php`,`${API_ROOT}/tv/data/projetos.json`]);return arr(j).map(p=>({raw:p,id:normId(p.id||p.codigo||p.tv_id||p.cronograma_id),nome:extractName(p),coord:extractCoord(p),updatedAt:extractUpdated(p),dias:daysSince(extractUpdated(p)),status:String(pick(p,['status','status_atual','texto','resumo','descricao','observacao','mensagem','statusAtual'],'Sem status informado na TV.')).trim(),farol:norm(pick(p,['farol','cor','sinal'],'')).toLowerCase(),execucao:String(pick(p,['execucao','execução','tipo_execucao'],'')).trim()})).filter(p=>p.nome);}
function matchByCron(item, list){let best=null,score=0; const sameCoord=list.filter(x=>x.coord===item.coord); const pool=sameCoord.length?sameCoord:list; for(const x of pool){let s=0; if(item.id&&x.id&&item.id===x.id)s=1; else s=similarity(item.nome,x.nome); if(s>score){score=s;best=x}} return score>=0.55?best:null;}
async function combustivelMes(){try{const j=await getJson(`${API_ROOT}/rh/combustivel/data/combustivel.json`); const ym=new Date().toISOString().slice(0,7); const itens=[]; if(Array.isArray(j))itens.push(...j); ['lancamentos','dados','data','items','registros'].forEach(k=>Array.isArray(j?.[k])&&itens.push(...j[k])); let total=0; itens.forEach(x=>{const data=String(x.data||x.date||x.dia||x.data_lancamento||''); if(!data||data.startsWith(ym)){let v=x.valor??x.value??x.total??x.valorTotal??0; if(typeof v==='string')v=Number(v.replace(/[^\d,.-]/g,'').replace(/\.(?=\d{3}(\D|$))/g,'').replace(',','.')); total+=Number(v)||0;}}); return total}catch(e){return 0}}
function chunk(a,n){const out=[]; for(let i=0;i<a.length;i+=n)out.push(a.slice(i,i+n)); return out;}
