(function(global){
  'use strict';
  const {Core,Importer,Engine,UI}=global.GPSV4;const $=id=>document.getElementById(id);let base=[],lastResult=null,mode='todos';
  function filteredEvents(){const plate=$('placa').value;const start=$('inicio').value?new Date($('inicio').value+'T00:00:00'):null;const end=$('fim').value?new Date($('fim').value+'T23:59:59'):null;return base.filter(x=>(!plate||x.plate===plate)&&(!start||x.dt>=start)&&(!end||x.dt<=end)).filter(x=>mode==='sabado'?x.dt.getDay()===6:mode==='domingo'?x.dt.getDay()===0:mode==='fora'?Core.outsideWork(x.dt):true)}
  function process(){lastResult=Engine.run(filteredEvents(),{showTechnical:$('mostrarTecnicos').checked});UI.render(lastResult);const discarded=lastResult.auditTrail.filter(x=>x.auditStatus.startsWith('DESCARTADO')||x.auditStatus.startsWith('SUBSTITUIDO')).length;UI.status(`${lastResult.cycles.length} ciclo(s), ${lastResult.segments.length} trecho(s) e ${discarded} evento(s) descartado(s) ou substituído(s).`,'ok')}
  $('arquivo').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;UI.status('Lendo e normalizando arquivo...');try{base=await Importer.readFile(file);if(!base.length)throw new Error('Não encontrei registros válidos. Confirme os cabeçalhos Data/Hora e Rastreável.');UI.fillFilters(base);process();UI.status(`Arquivo "${file.name}" carregado com ${base.length.toLocaleString('pt-BR')} eventos válidos.`,'ok')}catch(error){console.error(error);UI.status(error.message||'Falha ao ler o arquivo.','error')}});
  $('processar').addEventListener('click',process);$('mostrarTecnicos').addEventListener('change',process);
  $('limpar').addEventListener('click',()=>{mode='todos';document.querySelectorAll('.chip').forEach((c,i)=>c.classList.toggle('active',i===0));$('placa').value='';if(base.length){$('inicio').value=Core.iso(base[0].dt);$('fim').value=Core.iso(base[base.length-1].dt)}$('mostrarTecnicos').checked=false;process()});
  document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{mode=chip.dataset.mode;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));chip.classList.add('active');process()}));
  document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`panel-${tab.dataset.tab}`).classList.add('active')}));
  $('auditStatus').addEventListener('change',()=>lastResult&&UI.renderAuditRows(lastResult.auditTrail));$('exportarAuditoria').addEventListener('click',()=>lastResult&&UI.exportAudit(lastResult.auditTrail));
})(window);
