const API_BASE = "https://api.erpimpar.com.br/empreiteiros";
const API_OBRAS = "https://api.erpimpar.com.br/cronograma/listar_obras.php";

if(window.Swal && Swal.mixin){window.Swal=Swal.mixin({customClass:{popup:"impar-swal",confirmButton:"impar-swal-confirm",cancelButton:"impar-swal-cancel"},buttonsStyling:false});}

const estado={itens:[],medicoes:[],pagos:0,empreiteiros:[]};
function moeda(n){return Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function parseMoeda(v){if(typeof v==="number")return v;return Number(String(v||"0").replace(/[^\d,.-]/g,"").replace(/\./g,"").replace(",","."))||0;}
function dataISOHoje(){return new Date().toISOString().slice(0,10);}
function dataPorExtenso(iso){if(!iso)return"";const[y,m,d]=iso.split("-").map(Number);const meses=["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"];return `${d} de ${meses[m-1]} de ${y}`;}
function atualizarDataExtenso(){document.getElementById("dataExtenso").value=dataPorExtenso(document.getElementById("dataContrato").value);}
function numeroPorExtensoSimples(valor){const v=Math.round(parseMoeda(valor)); if(v===62699)return"sessenta e dois mil e seiscentos e noventa e nove reais"; return moeda(v).replace("R$","").trim()+" reais";}
function onValorContrato(){const v=parseMoeda(document.getElementById("valorContrato").value);document.getElementById("valorExtenso").value=numeroPorExtensoSimples(v);}
function novoItem(){return{id:estado.itens.length+1,descricao:"",quantidade:0,valorUnitario:0,valorTotal:0,percentualMedido:0};}
function adicionarItem(foco){estado.itens.push(novoItem());renderItens();if(foco){const inputs=document.querySelectorAll("#itensBody tr:last-child input");if(inputs[1])inputs[1].focus();}}
function removerItem(idx){estado.itens.splice(idx,1);estado.itens.forEach((it,i)=>it.id=i+1);renderItens();}
function renderItens(){const body=document.getElementById("itensBody");body.innerHTML="";estado.itens.forEach((it,idx)=>{const tr=document.createElement("tr");const saldo=Math.max(0,100-(Number(it.percentualMedido)||0));tr.innerHTML=`<td><input value="${it.id}" readonly></td><td><input value="${it.descricao||""}" placeholder="Descrição" data-field="descricao"></td><td><input value="${it.quantidade||""}" placeholder="Quantidade" data-field="quantidade"></td><td><input value="${it.valorUnitario?moeda(it.valorUnitario):""}" placeholder="Valor unitário" data-field="valorUnitario"></td><td><input value="${moeda(it.valorTotal)}" readonly></td><td><input value="${saldo.toFixed(2).replace(".",",")}%" readonly></td><td><button class="remove-btn" onclick="removerItem(${idx})">×</button></td>`;tr.querySelectorAll("input[data-field]").forEach(input=>{input.addEventListener("change",()=>{const field=input.dataset.field;if(field==="descricao")it.descricao=input.value;if(field==="quantidade")it.quantidade=parseMoeda(input.value);if(field==="valorUnitario")it.valorUnitario=parseMoeda(input.value);it.valorTotal=(Number(it.quantidade)||0)*(Number(it.valorUnitario)||0);renderItens();});input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();adicionarItem(true);}});});body.appendChild(tr);});atualizarResumo();}
function atualizarResumo(){const totalItens=estado.itens.reduce((s,it)=>s+(Number(it.valorTotal)||0),0);const valorTopo=parseMoeda(document.getElementById("valorContrato").value);const totalContrato=valorTopo || totalItens;const totalMedido=estado.itens.reduce((s,it)=>s+((Number(it.valorTotal)||0)*(Number(it.percentualMedido)||0)/100),0);const saldo=totalContrato-totalMedido;const percSaldo=totalContrato?Math.max(0,100-(totalMedido/totalContrato*100)):100;document.getElementById("kpiContrato").textContent=moeda(totalContrato);document.getElementById("kpiMedido").textContent=moeda(totalMedido);document.getElementById("kpiPago").textContent=moeda(estado.pagos);document.getElementById("kpiSaldo").textContent=moeda(saldo);document.getElementById("kpiSaldoPerc").textContent=percSaldo.toFixed(1).replace(".",",")+"%";}
function abrirModal(id){document.getElementById(id).setAttribute("aria-hidden","false");}function fecharModal(id){document.getElementById(id).setAttribute("aria-hidden","true");}
function abrirEmpreiteiro(){abrirModal("modalEmpreiteiro");}
async function salvarEmpreiteiro(){const dados={nome:val("empNome")||"Novo empreiteiro",contato:val("empContato"),cpf_contato:val("empCpfContato"),telefone:val("empTelefone"),cep:val("empCep"),cpf_cnpj:val("empDoc"),logradouro:val("empLogradouro"),numero:val("empNumero"),bairro:val("empBairro"),cidade:val("empCidade"),uf:val("empUf"),complemento:val("empComplemento"),email:val("empEmail")};try{await post(`${API_BASE}/salvar_empreiteiro.php`,dados);}catch(e){console.warn(e);}const select=document.getElementById("empreiteiro");const opt=document.createElement("option");opt.textContent=dados.nome;opt.value=dados.nome;select.appendChild(opt);select.value=dados.nome;fecharModal("modalEmpreiteiro");Swal.fire({icon:"success",title:"Empreiteiro cadastrado",text:"Cadastro adicionado e selecionado no contrato."});}
function val(id){return(document.getElementById(id)?.value||"").trim();}
function abrirMedicao(){if(!estado.itens.length){Swal.fire({icon:"warning",title:"Sem itens",text:"Adicione pelo menos um item na tabela base."});return;}document.getElementById("dataMedicao").value=dataISOHoje();const body=document.getElementById("medicaoBody");body.innerHTML="";estado.itens.forEach((it,idx)=>{const ja=Number(it.percentualMedido)||0;const saldoPerc=Math.max(0,100-ja);const tr=document.createElement("tr");tr.innerHTML=`<td>${it.id}</td><td>${it.descricao||"—"}</td><td>${moeda(it.valorTotal)}</td><td>${ja.toFixed(2).replace(".",",")}%</td><td><input type="number" min="0" max="${saldoPerc}" step="0.01" value="0" data-med-idx="${idx}"></td><td class="valor-med">${moeda(0)}</td><td class="saldo-med">${moeda((it.valorTotal||0)*(saldoPerc/100))}</td>`;body.appendChild(tr);});body.querySelectorAll("input[data-med-idx]").forEach(inp=>inp.addEventListener("input",calcularMedicaoModal));calcularMedicaoModal();abrirModal("modalMedicao");}
function calcularMedicaoModal(){let total=0;document.querySelectorAll("#medicaoBody tr").forEach(tr=>{const idx=Number(tr.querySelector("input[data-med-idx]").dataset.medIdx);const it=estado.itens[idx];const ja=Number(it.percentualMedido)||0;const saldoPerc=Math.max(0,100-ja);let p=Number(tr.querySelector("input[data-med-idx]").value)||0;if(p>saldoPerc)p=saldoPerc;const valorMed=(Number(it.valorTotal)||0)*p/100;const saldoApos=(Number(it.valorTotal)||0)*Math.max(0,(saldoPerc-p))/100;tr.querySelector(".valor-med").textContent=moeda(valorMed);tr.querySelector(".saldo-med").textContent=moeda(saldoApos);total+=valorMed;});document.getElementById("totalMedicaoAtual").textContent=moeda(total);}
async function confirmarMedicao(){const data=val("dataMedicao")||dataISOHoje();const obs=val("obsMedicao");const itensMedidos=[];let total=0;document.querySelectorAll("#medicaoBody tr").forEach(tr=>{const idx=Number(tr.querySelector("input[data-med-idx]").dataset.medIdx);const it=estado.itens[idx];let p=Number(tr.querySelector("input[data-med-idx]").value)||0;const saldoPerc=Math.max(0,100-(Number(it.percentualMedido)||0));if(p>saldoPerc)p=saldoPerc;const valor=(Number(it.valorTotal)||0)*p/100;if(p>0){it.percentualMedido=(Number(it.percentualMedido)||0)+p;total+=valor;itensMedidos.push({item:it.id,descricao:it.descricao,percentual:p,valor});}});if(!itensMedidos.length){Swal.fire({icon:"warning",title:"Medição zerada",text:"Informe pelo menos um percentual realizado."});return;}const medicao={id:"MED-"+String(estado.medicoes.length+1).padStart(3,"0"),data,obs,total,itens:itensMedidos,notificacao:{diretoria:true,financeiro:true,whatsapp_pendente:true}};estado.medicoes.push(medicao);try{const resp=await post(`${API_BASE}/salvar_medicao.php`,{contrato:montarPayload(),medicao}); if(resp && resp.pdf_url) window.open(resp.pdf_url,"_blank");}catch(e){console.warn(e);}fecharModal("modalMedicao");renderItens();Swal.fire({icon:"success",title:"Medição registrada",html:`Histórico gravado.<br><br><b>Total a pagar:</b> ${moeda(total)}<br><br>PDF e notificação ficam preparados no back-end.`});}
async function gerarContrato(){const payload=montarPayload();try{const resp=await post(`${API_BASE}/salvar_contrato.php`,payload);Swal.fire({icon:"success",title:"Contrato salvo",html:`Contrato gravado.<br><br><b>ID:</b> ${resp.id||"—"}<br><br>Use o template DOCX do pacote para geração final.`});}catch(e){Swal.fire({icon:"error",title:"Erro ao salvar contrato",text:e.message});}}
function montarPayload(){return{obra:val("obra"),empreiteiro:val("empreiteiro"),condicoes_pagamento:val("condicoesPagamento"),valor_contrato:parseMoeda(val("valorContrato")),valor_extenso:val("valorExtenso"),data:val("dataContrato"),data_extenso:val("dataExtenso"),prazo_dias:Number(val("prazoDias"))||0,itens:estado.itens,medicoes:estado.medicoes,conta_corrente:{total_contrato:parseMoeda(val("valorContrato")),total_medido:estado.itens.reduce((s,it)=>s+((Number(it.valorTotal)||0)*(Number(it.percentualMedido)||0)/100),0),total_pago:estado.pagos,saldo:parseMoeda(val("valorContrato"))-estado.itens.reduce((s,it)=>s+((Number(it.valorTotal)||0)*(Number(it.percentualMedido)||0)/100),0)},meta:{criado_em:new Date().toISOString(),origem:"contrato_empreiteiro_rebuild_v2"}};}
async function post(url,data){const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const txt=await res.text();let js={};try{js=JSON.parse(txt);}catch(e){}if(!res.ok||js.success===false)throw new Error(js.error||txt||"Erro no servidor");return js;}
async function carregarEmpreiteiros(){try{const r=await fetch(`${API_BASE}/listar_empreiteiros.php?t=${Date.now()}`);const js=await r.json();const sel=document.getElementById("empreiteiro");(js.empreiteiros||[]).forEach(e=>{const o=document.createElement("option");o.value=e.nome||e.razao_social;o.textContent=e.nome||e.razao_social;sel.appendChild(o);});}catch(e){const sel=document.getElementById("empreiteiro");["Abilio Serafim Construtora Ltda"].forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;sel.appendChild(o);});}}
async function carregarObras(){try{const r=await fetch(`${API_OBRAS}?t=${Date.now()}`);const js=await r.json();const arr=Array.isArray(js)?js:(js.obras||js.data||[]);const sel=document.getElementById("obra");arr.forEach(o=>{const nome=o.nome||o.Nome||o.obra||o.Obra||String(o);const op=document.createElement("option");op.value=nome;op.textContent=nome;sel.appendChild(op);});}catch(e){["Cooperativa Fumacense","FIESC","Giassi Araranguá"].forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;document.getElementById("obra").appendChild(o);});}}
function popularInicial(){estado.itens=[{id:1,descricao:"Descrição",quantidade:1,valorUnitario:0,valorTotal:0,percentualMedido:0}];renderItens();atualizarDataExtenso();}
window.addEventListener("DOMContentLoaded",()=>{document.body.classList.add("impar-enter");carregarObras();carregarEmpreiteiros();popularInicial();});